on:
  push:
    branches:
      - feature/ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SCP
        run: scp -r ./* ${{ secrets.VPS_USER}}@s66.mydevil.net/domains/digishop.royal622.usermd.net/test/

#      - name: Execute deployment script
#        run: ssh user@your_vps_ip 'bash /path/to/deploy/deploy_script.sh'
