name: DeployTestCheckWorkflow

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
jobs:
  deploy:
    name: Deploy on VPS
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: .

      - name: List downloaded files
        run: ls -l

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "s66.mydevil.net,128.204.219.135 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPym/HwhTsEmByk+0PRCrMOsr29xXA8kG5rLTzj5WjMl5DwVf6WdysNAsWw3GcyOzjVQxpVgrakHihnaqth/+yM=" > ~/.ssh/known_hosts

      - name: Copy files via SCP
        run: scp ${{ github.run_id }}.zip ${{ secrets.VPS_USER }}@${{secrets.VPS_HOST}}:domains/digishop.royal622.usermd.net/zip/

      - name: Run deploy script on VPS
        run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'cd domains/digishop.royal622.usermd.net && /bin/bash deploy.sh'
