name: GitHub Pipelines

on:
  push:
    branches:
      - develop
      - feature/*
      - main
  pull_request:
    branches:
      - develop
      - feature/*
      - main

jobs:
  set-variables:
    runs-on: ubuntu-20.04
    outputs:
      is_develop: ${{ steps.set-vars.outputs.is_develop }}
      is_main: ${{ steps.set-vars.outputs.is_main }}
      is_cicd_test: ${{ steps.set-vars.outputs.is_cicd_test }}
      can_deploy_on_dev: ${{ steps.set-vars.outputs.can_deploy_on_dev }}
      can_deploy_on_production: ${{ steps.set-vars.outputs.can_deploy_on_production }}
    steps:
      - name: Set variables
        id: set-vars
        run: |
          IS_DEVELOP=false
          IS_MAIN=false
          IS_CICD_TEST=false
          CAN_DEPLOY_ON_DEV=false
          CAN_DEPLOY_ON_PRODUCTION=false

          if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            IS_DEVELOP=true
            CAN_DEPLOY_ON_DEV=true
          fi

          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            IS_MAIN=true
            CAN_DEPLOY_ON_PRODUCTION=true
          fi

          if [[ "${GITHUB_REF}" == refs/heads/feature/ci-cd* ]]; then
            IS_CICD_TEST=true
            CAN_DEPLOY_ON_DEV=true
          fi

          echo "is_develop=$IS_DEVELOP" >> $GITHUB_ENV
          echo "is_main=$IS_MAIN" >> $GITHUB_ENV
          echo "is_cicd_test=$IS_CICD_TEST" >> $GITHUB_ENV
          echo "can_deploy_on_dev=$CAN_DEPLOY_ON_DEV" >> $GITHUB_ENV
          echo "can_deploy_on_production=$CAN_DEPLOY_ON_PRODUCTION" >> $GITHUB_ENV


